language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2
before_script:
  - cd wallbase-web//src/main/resources
  - pwd
  - npm install -g gulp-cli
  - npm install
  - gulp clean
  - gulp build
script:
  - cd $TRAVIS_BUILD_DIR
  - pwd
  - mvn clean install -Dmaven.test.skip=true
after_script:
  - cp wallbase-web/target/wallbase-web-1.0-SNAPSHOT.jar ./
deploy:
#  provider: releases
  provider: pages
  github_token: $access_tokens
#  file:
#    - "wallbase-web/target/wallbase-web-1.0-SNAPSHOT.jar"
  skip_cleanup: true
  on:
#     tags: true
     branch: master
