language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

script:
  - mvn clean install -Dmaven.test.skip=true
  
deploy:
  provider: releases
  api_key: $access_tokens
  file:
    - "wallbase-web/target/wallbase-web-1.0-SNAPSHOT.jar"
  skip_cleanup: true
  on:
     tags: true
     branch: master
