spring:
  application:
    name: tractor
  profiles:
    active: local
  http:
      multipart:
        max-file-size: 20Mb
        max-request-size: 20Mb
      encoding:
        charset: utf-8
        force: true
  mvc:
    favicon:
      enabled: false
  aop:
    auto: false
    proxy-target-class: true
  freemarker:
    cache: false
  mail:
    host: smtp.mxhichina.com
    port: 25
    username: wang.kun@zhongfl.com
    password: WANGKUN

server:
  context-path: /
  compression:
    enabled: true
  port: 9090

logback:
  access:
    enabled: false