# application.yml
mybatis:
  mapper-locations: classpath:/mybatis/*Mapper.xml
  config-location:  classpath:mybatis-config.xml
  type-aliases-package:tv.wallbase.gateway.domain
  type-handlers-package: tv.wallbase.mapper.typehandler
  configuration:
      map-underscore-to-camel-case: true
      default-fetch-size: 100
      default-statement-timeout: 30